In [9]:
import pandas as pd
from scipy import stats
import statistics
df=pd.read_excel("data_M5.xlsx", usecols=[1,2,3,4,5])

df

for i in df:
    print('---%s---'%i) #to print title
    Q1=df[i].quantile(0.25)
    print('Q1 =',Q1)
    Q2=df[i].quantile(0.5) 
    print('Q2 =',Q2)
    Q3=df[i].quantile(0.75) 
    print('Q3 =',Q3)
    Rata=df[i].mean()
    print('Mean =',Rata)
    Me=df[i].median()
    print('Median =',Me)
    Std_dev=statistics.stdev(df[i])
    print('Std Dev =',Std_dev)
    Skewness=df[i].skew()
    print('Skewness =',Skewness,'\n')

---x1---
Q1 = 49.75
Q2 = 66.5
Q3 = 81.25
Mean = 65.37
Median = 66.5
Std Dev = 20.86883278523698
Skewness = -0.16419238167815509

---x2---
Q1 = 47.0
Q2 = 68.5
Q3 = 86.25
Mean = 65.91
Median = 68.5
Std Dev = 22.99279421598397
Skewness = -0.27951524951443163

---x3---
Q1 = 37.0
Q2 = 57.0
Q3 = 72.0
Mean = 53.94
Median = 57.0
Std Dev = 24.06884905743303
Skewness = -0.08572766115102076

---x4---
Q1 = 47.75
Q2 = 60.0
Q3 = 75.25
Mean = 61.62
Median = 60.0
Std Dev = 18.415946098614395
Skewness = 0.09285712075934789

---x5---
Q1 = 55.0
Q2 = 70.5
Q3 = 83.5
Mean = 67.47
Median = 70.5
Std Dev = 21.003345091925357
Skewness = -0.5428913112544221

In [10]:
df.describe()

               x1          x2          x3          x4          x5
count  100.000000  100.000000  100.000000  100.000000  100.000000
mean    65.370000   65.910000   53.940000   61.620000   67.470000
std     20.868833   22.992794   24.068849   18.415946   21.003345
min     20.000000   21.000000   10.000000   16.000000   21.000000
25%     49.750000   47.000000   37.000000   47.750000   55.000000
50%     66.500000   68.500000   57.000000   60.000000   70.500000
75%     81.250000   86.250000   72.000000   75.250000   83.500000
max    100.000000  100.000000  100.000000   99.000000  100.000000